twig:
    paths: ['%kernel.project_dir%/templates']
    form_themes: ['form/color_theme.html.twig']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    Twig\Extra\Intl\IntlExtension: ~
